name: agents-deploy

on:
  push:
    branches:
      - main # Trigger on push to main branch
      - dev # Trigger on push to dev branch

permissions:
  contents: read
  id-token: write

env:
  SERVICE_NAME: ${{ github.ref_name == 'dev' && format('{0}-dev', vars.SERVICE_NAME) || vars.SERVICE_NAME }}
  IMAGE_NAME: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ vars.ARTIFACT_REPO }}/${{ github.ref_name == 'dev' && format('{0}-dev', vars.SERVICE_NAME) || vars.SERVICE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/964317129318/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@edunova-455712.iam.gserviceaccount.com
          token_format: access_token

      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ vars.REGION }}
          image: ${{ env.IMAGE_NAME }}:latest
